# More Working on Arrays

In [1]:
import numpy as np

## Indexing in 1-D Arrays

In [4]:
a=[]
size=int(input("Enter size : "))
for i in range(size):
    num=int(input("Enter number : "))
    a.append(num)
arr=np.array(a)
for i in range(arr.size):
    print(arr[i])

sum=0
for i in range(arr.size):
    sum=sum+arr[i]
print('sum : ',sum)

Enter size : 3
Enter number : 1 
Enter number : 5
Enter number : 7
1
5
7
sum :  13


## Slicing in 1-D Arrays

In [5]:
# arr_name[start:end:step]
# arr_name[start:end+1]
# arr_name[start: ]
# arr_name[ :end+1]
# arr_name[ : ]

In [10]:
a1=[]
size=int(input("Enter size : "))
for i in range(size):
    num1=int(input("Enter number : "))
    a1.append(num1)
arr1=np.array(a1)
for i in range(arr1.size):
    print(arr1[i])

a2=arr1[1::2]
print(a2)

Enter size : 8
Enter number : 4 
Enter number : 2
Enter number : 5
Enter number : 2
Enter number : 1
Enter number : 7
Enter number : 5
Enter number : 0
4
2
5
2
1
7
5
0
[2 5 2 1 7]


## Reshaping of Arrays

In [20]:
arr=np.random.randint(1,50,12)
print(arr.shape)

arr1=arr.reshape(3,4)
print(arr1)
print(arr1.shape)

arr2=arr.reshape(4,3)
print(arr2)

arr3=arr.reshape(2,6)
print(arr3)

# when column or row is unknown
arr4=arr.reshape(4,-1)
print(arr4)

(12,)
[[29 16 30 13]
 [19 48 18 40]
 [ 6  7 30 28]]
(3, 4)
[[29 16 30]
 [13 19 48]
 [18 40  6]
 [ 7 30 28]]
[[29 16 30 13 19 48]
 [18 40  6  7 30 28]]
[[29 16 30]
 [13 19 48]
 [18 40  6]
 [ 7 30 28]]


## Seed Function in NumPy

In [29]:
# We use seed to generate fix set of random numbers.

np.random.seed(12)
arr=np.random.randint(1,100,10) 
arr

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])