# Numpy Functions 

In [2]:
import numpy as np

### 1. Zeros

In [10]:
arr1=np.zeros(5)
arr2=np.zeros((2,3))
print('1-D : ',arr1)
print('2-D : ',arr2)

1-D :  [0. 0. 0. 0. 0.]
2-D :  [[0. 0. 0.]
 [0. 0. 0.]]


### 2. Ones

In [16]:
a1=np.ones(4)
a2=np.ones((2,2))
print(a1)
print(a2)

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]


### 3. Eye 

In [19]:
# This function creates an array with all the diagonal elements as 1 and rest as 0(in square matrix),
# In case of a non-square matrix, the values are still 1 for diagonal(upto  which it can draw diagonal) and rest are zero.

a3=np.eye(3)
a4=np.eye(3,4)
print(a3)
print(a4)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


### 4. Diag

In [27]:
# This funtion creates a 2-dimensional array with all the diagonal elements as the given value and rest as 0(in a square matrix).

a5=np.diag([1,2,3,4])
np.diag(a5)
# print(a5)

array([1, 2, 3, 4])

### 5. Randint

In [30]:
# This function is used to generate random number between a given range.
# rand(min,max,total_no_of_values)

a6=np.random.randint(1,11,2)
a6

array([3, 3])

### 6. Rand

In [35]:
# This function is used to generate random values between 0 to 1
# rand(no_of_values)

a7=np.random.rand(4)
a8=np.random.rand(2,2)
print(a7)
print(a8)

[0.63079073 0.22110635 0.24192978 0.0921116 ]
[[0.96454879 0.30079917]
 [0.24728316 0.65958519]]


### 7. Randn

In [36]:
# This function is used to generate random values close to 0. This may return positive and negative numbers.
# rand(no_of_values)

a9=np.random.randn(3)
a9

array([-0.85193254, -0.81796456,  0.84964643])