# Working on 2-D Arrays

In [1]:
import numpy as np

## Indexing in 2-D Arrays

In [ ]:
matrix=[]
row=int(input("Enter no of rows: "))
col=int(input("Enter no of columns: "))
for i in range(row):
    a=[]
    for j in range(col):
        val=int(input("Enter value: "))
        a.append(val)
    matrix.append(a)
# converting the matrix into 2-D array
arr=np.array(matrix)
for i in range(row):
    for j in range(col):
        print(arr[i,j], end=" ")
    print()
print(type(arr))

## Slicing 

In [11]:
a = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a)

# a[row range, col range]
print(a[:2])     # returns row from 0 to 1 and since col is not given then all cols are printed
print(a[:2,1:3])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[10 20 30]
 [40 50 60]]
[[20 30]
 [50 60]]


In [21]:
np.random.seed(100)
a=np.random.randint(1,500,24).reshape(4,6)
print(a)

print(a[1:,3:])

[[  9 281 324 360 344  80]
 [433 395 351 437 355  54]
 [ 67 227  15 291 498 241]
 [281 144 229 364 317  59]]
[[437 355  54]
 [291 498 241]
 [364 317  59]]
