In [7]:
import numpy as np

# Some Functions


## 1. Arange

In [13]:
# returns a list of numbers from start to end.
A1 = np.arange(100)
A2 = np.arange(20,100,10)
print(A1)
print(A2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[20 30 40 50 60 70 80 90]


## 2. Range


In [14]:
print(range(0,10))

range(0, 10)


In [15]:
print(list(range(0,10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [16]:
print(tuple(range(0,20,2)))

(0, 2, 4, 6, 8, 10, 12, 14, 16, 18)


## 3. Random

In [18]:
# random.permutation
A = np.random.permutation(np.arange(10))
print(A)

[1 9 4 0 3 2 5 6 7 8]


In [21]:
# random.randint
np.random.randint(10,20)

14

In [24]:
A = np.random.rand(10)
print(A)

[0.45130804 0.75367867 0.93471554 0.12481698 0.95949426 0.03059149
 0.06432955 0.95096203 0.9868606  0.08392326]


In [26]:
B = np.random.rand(2,4)
print(B)

[[0.75833048 0.56352331 0.20539258 0.01646787]
 [0.67327188 0.5944224  0.76596431 0.74024389]]


## 4. Reshape

In [28]:
# reshape array
C = np.arange(100).reshape(4,25)
print(C.shape)

(4, 25)